### ISSUE TITLE
Stripe Plan Creation with Tiers

### ISSUE THREAD

**Issue by nrobates** [adrienverge/localstripe#44] opened 2018-12-10 19:51 UTC
Trying to use this to create a Plan. However this is the error I keep getting:
`Stripe\Error\InvalidRequest: Unexpected billing_scheme, tiers_mode, usage_type, tiers`

Am I missing something here. I thought this was following the latest version of Stripe API. What version is this supporting? 

Many thanks in advance. Would love to use this package for sure, however need this part to work in order to even continue.

**Comment by adrienverge** [comment] 2018-12-10 21:43
Hi,

This is trying to follow the latest version of the API, yes, but not all features are implemented yet.

If these are simple options, you can try to contribute. For example here are recent contributions to add options for plans: https://github.com/adrienverge/localstripe/pull/29 https://github.com/adrienverge/localstripe/pull/35.

**Comment by nrobates** [comment] 2019-01-17 19:50
@marotpam / @adrienverge Just tried out the latest docker image which I expected contained the support for tiered pricing. However, if I use the same example for testing provided or the following, there is an invalid request error returned. Here is an example:

```
curl localhost:8420/v1/plans -u sk_test_12345: \
   -d id=annual-tiered \
   -d name='Annual tiered' \
   -d currency=eur \
   -d interval=year \
   -d interval_count=1 \
   -d usage_type=licensed \
   -d billing_scheme=tiered \
   -d tiers_mode=volume \
   -d tiers[0][unit_amount]=1500 \
   -d tiers[0][up_to]=10 \
   -d tiers[1][unit_amount]=1000 \
   -d tiers[1][up_to]=inf \
```

The response is:
```
{
  "error": {
    "message": "Unexpected billing_scheme, tiers_mode, tiers",
    "type": "invalid_request_error"
  }
}
```

Just wondering if either the tiered support did not make it in, or if there is a bug still. Many Thanks.

**Comment by adrienverge** [comment] 2019-01-17 22:02
@nrobates thanks for reporting that. I guess I pushed a wrong version to dockerhub. Could you try again now?

**Comment by nrobates** [comment] 2019-01-18 00:19
@adrienverge yes that fixed the error I was receiving. However there is a few other things that I noticed. 

1. When creating a Plan, Stripe asks for `nickname` not `name`.
2. It would be great to not have to pass `id` along and it could auto-generate by slugging the nickname or something, it is something that can be worked around.

Thanks!

**Comment by marotpam** [comment] 2019-01-18 09:30
Hi @nrobates, glad the tiered pricing is working.

@adrienverge I think it would be a good idea to have travis push the latest docker image on successful builds after pushes to master, this way you wouldn't need to manually push the docker images. WDYT?
A possible approach for that could consist of adding something similar to this in the travis config:
```
deploy:
  provider: script
  script:
    - docker push ....
  on:
    branch: master
```

**Comment by nrobates** [comment] 2019-01-18 18:15
@marotpam / @adrienverge I have been doing a great deal of testing and my god it's so close. I got the tiered plans working great for creation. However there is a use-case where this is a problem now. When you create a subscription to a tiered plan, it fails with bad request. I was looking in the `resources.py` file under the subscription section. I believe the issue happens in the `_set_up_subscription_and_invoice` method as it is trying to use the `amount` which in the tiered approach is `null`.

**Comment by nrobates** [comment] 2019-02-13 16:21
@marotpam / @adrienverge I hope all is going well. I just wanted to touch base and see if there are any updates on the last issue I posted regarding the tiered plans and the issue with the `_set_up_subscription_and_invoice` method. Many thanks in advance!

**Comment by adrienverge** [comment] 2019-02-13 16:25
@nrobates thanks for your report! I will take time to review any contribution to fix this.

**Comment by marotpam** [comment] 2019-02-13 18:15
Hi @nrobates , I actually spent some time looking into this, but then I realized that there are some other missing features in localstripe related to this topic. 
As an example, at the moment there is no support for having a subscription with multiple plans (which is [supported by Stripe](https://stripe.com/docs/billing/subscriptions/multiplan)), or subscribing multiple times to the same plan (by setting the `quantity` of the plan upon subscription creation). 
I don't know if @adrienverge has any plans to implement these features in the future, but if you only need subscriptions to one plan with tiered billing then I can open a PR with just those changes, and we can treat the missing features as separate issues

**Comment by nrobates** [comment] 2019-02-13 18:20
Hi @marotpam. Yes those are good points. However for my needs currently, it is just a single subscription with just a single plan that I am trying to use and test against. I would think that treating the missing features as separate issues would be best as they are extended complexity from just the basic support at a granular level.

**Comment by nrobates** [comment] 2019-06-12 23:21
Hi @marotpam and @adrienverge. I finally was able to pull the latest docker image and do some testing. I am getting some errors during the create subscription portion though. From what I see it is because it is looking for a `from` parameter inside of the tier properties. However there is no such thing as a `from` property for a tier. Here is the error traceback:

```
stripetest_1  | Error handling request
stripetest_1  | Traceback (most recent call last):
stripetest_1  |   File "/usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
stripetest_1  |     resp = await task
stripetest_1  |   File "/usr/local/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
stripetest_1  |     resp = await handler(request)
stripetest_1  |   File "/usr/local/lib/python3.7/site-packages/aiohttp/web_middlewares.py", line 119, in impl
stripetest_1  |     return await handler(request)
stripetest_1  |   File "/usr/local/lib/python3.7/site-packages/localstripe/server.py", line 55, in error_middleware
stripetest_1  |     return await handler(request)
stripetest_1  |   File "/usr/local/lib/python3.7/site-packages/localstripe/server.py", line 185, in auth_middleware
stripetest_1  |     return await handler(request)
stripetest_1  |   File "/usr/local/lib/python3.7/site-packages/localstripe/server.py", line 197, in f
stripetest_1  |     return json_response(cls._api_create(**data)._export())
stripetest_1  |   File "/usr/local/lib/python3.7/site-packages/localstripe/resources.py", line 119, in _api_create
stripetest_1  |     return cls(**data)
stripetest_1  |   File "/usr/local/lib/python3.7/site-packages/localstripe/resources.py", line 1369, in __init__
stripetest_1  |     self._set_up_subscription_and_invoice(plan)
stripetest_1  |   File "/usr/local/lib/python3.7/site-packages/localstripe/resources.py", line 1418, in _set_up_subscription_and_invoice
stripetest_1  |     amount=si._calculate_amount(),
stripetest_1  |   File "/usr/local/lib/python3.7/site-packages/localstripe/resources.py", line 1541, in _calculate_amount
stripetest_1  |     (i for i, t in enumerate(self.plan.tiers)
stripetest_1  |   File "/usr/local/lib/python3.7/site-packages/localstripe/resources.py", line 1543, in <genexpr>
stripetest_1  |     or int(t['from']) <= self.quantity <= int(t['up_to'])))
stripetest_1  | KeyError: 'from'
stripetest_1  | ::ffff:172.29.0.3 [12/Jun/2019:23:04:43 +0000] "POST /v1/subscriptions HTTP/1.1" 500 244 "-" "Stripe/v1 PhpBindings/6.28.1"
```

**Comment by adrienverge** [comment] 2019-06-13 07:01
Hi @nrobates,

I looked at [Stripe docs on plans](https://stripe.com/docs/api/plans/create) and agree there is no `from` in tiers. I couldn't find `from` in previous API versions, neither (by reading at [the API changelog](https://stripe.com/docs/upgrades#api-changelog)).

But I'm not a tiered usage specialist, I've never used it...

@marotpam when you created eb0749c, which Stripe API version were you replicating? Do you have any info on this `from` parameter? Actually we don't even validate it in plan creation checks: https://github.com/adrienverge/localstripe/blob/f912c25/localstripe/resources.py#L1108-L1116

**Comment by marotpam** [comment] 2019-06-13 16:57
Hi @nrobates @adrienverge you're right, I can't see `from` referenced in the docs, which is weird. 
Honestly I don't remember the reasoning behind adding it in the first place, but it is needed to [calculate](https://github.com/adrienverge/localstripe/commit/eb0749c3438074728f2acfe7bab8ef5fa4177f6e#diff-62ee820ebbbef6539c97fecb3a10c374R1483) invoice amounts for tiered plans. Instead reading it from the tier definition, we need to calculate it by looking at the `up_to` value of the previous tier. 
I will try to find some time over the weekend to do that, sorry for the inconvenience

**Comment by rasmuscnielsen** [comment] 2020-01-03 13:55
@adrienverge @marotpam I can confirm this exact issue as I'm progressing with my test suite 😄 

No reference to `from` in Stripe API and it works as expected without, so at the very least it's optional.
https://github.com/adrienverge/localstripe/blob/b0515c8e313e3eaed4c9af5fbf961ef3cdcb3fea/localstripe/resources.py#L2577

I have not yet tested it, but would believe changing the above line to the following would work as expected:

` or self.quantity <= int(t['up_to'])))`

Given that there seems consensus on this being an issue, would that be an acceptable fix @adrienverge  ?

**Comment by marotpam** [comment] 2020-01-03 15:56
Hi @rasmuscnielsen, thanks for your time invested on this issue. The solution for it required a little bit more work than you mentioned, but thanks for pointing that out as it saved me some time when fixing it (see https://github.com/adrienverge/localstripe/pull/114). Hope everything works on your end after this!

**Comment by adrienverge** [comment] 2020-01-17 15:51
@rasmuscnielsen @marotpam please excuse me for the long delay! The issue should be fixed now, thanks to Marcel.

**Closed by adrienverge** 2020-01-17 15:51 UTC
